 const actionTypes = {
     CALL:"CALL",
     ADD_CLASS_INITIATE:'ADD_CLASS_INITIATE',
     ADD_STUDENT_INITIATE:"ADD_STUDENT_INITIATE",
     ADD_COLUMN_INITIATE:"ADD_COLUMN_INITIATE",
     ADD_SUBJECTS_INITIATE:"ADD_SUBJECTS_INITIATE",
     ADD_ATTENDENCE_INITIATE:"ADD_ATTENDENCE_INITIATE",
     ADD_NEW_RESULT_INITATE:"ADD_NEW_RESULT_INITATE",
     EDIT_RESULT_INITATE:'EDIT_RESULT_INITATE',
     CLASS_MESSAGE_INITATE:'CLASS_MESSAGE_INITATE',
     STUDENT_MSG_INITIATE:'STUDENT_MSG_INITIATE',
     ADD_POST_INITIATE:'ADD_POST_INITIATE',
     ADD_YEARLY_PLAN:'ADD_YEARLY_PLAN'
}
export default actionTypes;
