 const actionTypes = {
     CALL:"CALL",
     ADD_CLASS_INITIATE:'ADD_CLASS_INITIATE',
     ADD_STUDENT_INITIATE:"ADD_STUDENT_INITIATE",
     ADD_COLUMN_INITIATE:"ADD_COLUMN_INITIATE",
     ADD_SUBJECTS_INITIATE:"ADD_SUBJECTS_INITIATE",
     ADD_ATTENDENCE_INITIATE:"ADD_ATTENDENCE_INITIATE"
}
export default actionTypes;
